server:
  port: 8080


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true